substitutions:
  name: geodan-heatpump
  friendlyName: Geodan Heatpump

esphome:
  name: ${name}
  friendly_name: ${friendlyName}

esp32:
  board: esp32-s3-devkitm-1
  framework:
    type: esp-idf
    version: recommended
    # Custom sdkconfig options
    sdkconfig_options:
      COMPILER_OPTIMIZATION_SIZE: y

packages:
  ecodan-heatpump: github://mesomorf1/esphome-geodan-heatpump/heatpump.yaml@main

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

ota:
  #password: !secret heatpump_ota_password
  platform: esphome

